# Generated by Django 3.1.13 on 2022-01-02 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('activated_at', models.DateTimeField(null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('last_sold_at', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
